version: "3.7"

services:

  spring_security:
    image: niteshjha2021/springsecurity-production:latest
    networks:
      - spring-sec-net
    ports:
      - 80:8080
    depends_on:
      - mysql_db
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 120s
    restart: on-failure
    container_name: spring_security

  mysql_db:
    image: mysql:5
    networks:
      - spring-sec-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=springsecurity
    volumes:
      - mysql_db:/var/lib/mysql
    container_name: mysql_db
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 120s

networks:
  spring-sec-net:

volumes:
  mysql_db: